server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ticketing}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:verysecretkey}
  expirationMs: 86400000


spring:
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:25}
    username: ${MAIL_USER:}
    password: ${MAIL_PASS:}
    properties.mail.smtp.auth: false
    properties.mail.smtp.starttls.enable: false

file:
  upload-dir: ${UPLOAD_DIR:uploads}
